name: mainExpected

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-check:
    runs-on: ubuntu-latest
    steps:
      - name: ✅ Status check for "mainExpected"
        run: echo "All good."
